"""add ondelete cascade to questions

Revision ID: 51acd0300351
Revises: cff696c5bab3
Create Date: 2025-11-13 13:23:19.331648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51acd0300351'
down_revision = 'cff696c5bab3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'choices',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='choices::jsonb')
    op.alter_column('question', 'correct_choices',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='correct_choices::jsonb')
    op.create_index(op.f('ix_question_test_id'), 'question', ['test_id'], unique=False)
    op.drop_constraint(op.f('question_test_id_fkey'), 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'test', ['test_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_test_owner_id'), 'test', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_owner_id'), table_name='test')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key(op.f('question_test_id_fkey'), 'question', 'test', ['test_id'], ['id'])
    op.drop_index(op.f('ix_question_test_id'), table_name='question')
    op.alter_column('question', 'correct_choices',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('question', 'choices',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
